// Protocol configuration with DeFiLlama slugs for TVL fetching
// Data updated: February 2026
export const PROTOCOL_CONFIG = [
  {
    id: 1,
    slug: "babylon-finance",
    urlSlug: "babylon",
    name: "Babylon Labs",
    category: "Native Staking",
    apy: 0.5,
    apyRange: [0.29, 1.0],
    tvl: 5920,
    risk: "Low",
    chain: "Bitcoin",
    lockup: "21 days",
    minDeposit: 0.01,
    description: "Native BTC staking securing PoS chains. Rewards paid in BABY tokens. No wrapping, no bridges.",
    website: "https://babylonlabs.io",
    token: "BABY",
    audits: 4,
    auditors: ["Halborn", "CertiK", "Zellic", "Trail of Bits"],
    mechanics: [
      "Stake BTC directly on Bitcoin mainnet via time-lock scripts",
      "Secure proof-of-stake networks and earn BABY token rewards",
      "No wrapping, bridging, or custody transfer required",
      "Slashing protection through cryptographic finality gadgets"
    ],
    logo: "₿",
    color: "#F7931A",
    trend: [0.3, 0.35, 0.42, 0.38, 0.5, 0.55, 0.48, 0.6, 0.52, 0.45, 0.5, 0.5]
  },
  {
    id: 2,
    slug: "lombard",
    urlSlug: "lombard",
    name: "Lombard Finance",
    category: "Liquid Staking",
    apy: 0.4,
    apyRange: [0.4, 15.0],
    tvl: 1040,
    risk: "Low",
    chain: "Ethereum",
    lockup: "None",
    minDeposit: 0.0002,
    description: "LBTC liquid staking token via Babylon. Full DeFi composability. Up to 15% APY with BARD staking.",
    website: "https://lombard.finance",
    token: "LBTC",
    audits: 4,
    auditors: ["Halborn", "Zellic", "Spearbit", "Code4rena"],
    mechanics: [
      "Deposit BTC and receive LBTC liquid staking token 1:1",
      "LBTC earns Babylon staking rewards automatically",
      "Use LBTC across DeFi for additional yield opportunities",
      "Stake BARD tokens for boosted APY up to 15%"
    ],
    logo: "◆",
    color: "#6EE7B7",
    trend: [0.5, 0.45, 0.42, 0.38, 0.35, 0.4, 0.42, 0.38, 0.4, 0.4, 0.4, 0.4]
  },
  {
    id: 3,
    slug: "solv-protocol",
    urlSlug: "solvbtc",
    name: "SolvBTC",
    category: "Yield Vault",
    apy: 5.0,
    apyRange: [5.0, 10.0],
    tvl: 2000,
    risk: "Medium",
    chain: "Multi-chain",
    lockup: "7 days",
    minDeposit: 0.005,
    description: "Cross-chain yield optimization via xSolvBTC and SolvBTC.CORE. 1:1 backed with Chainlink PoR verification.",
    website: "https://solv.finance",
    token: "SolvBTC",
    audits: 3,
    auditors: ["Quantstamp", "SlowMist", "Secbit"],
    mechanics: [
      "Deposit BTC to mint SolvBTC universal reserve token",
      "Automated yield strategies across multiple chains",
      "Chainlink Proof of Reserve verifies 1:1 backing every 10 min",
      "xSolvBTC and SolvBTC.CORE for liquid staking rewards"
    ],
    logo: "◈",
    color: "#A78BFA",
    trend: [4.5, 5.2, 6.8, 5.5, 7.2, 6.0, 5.8, 4.8, 5.5, 5.2, 4.9, 5.0]
  },
  {
    id: 4,
    slug: "pendle",
    urlSlug: "pendle",
    name: "Pendle BTC",
    category: "Yield Trading",
    apy: 7.4,
    apyRange: [7.0, 18.0],
    tvl: 5800,
    risk: "High",
    chain: "Ethereum",
    lockup: "Variable",
    minDeposit: 0.01,
    description: "Tokenized yield trading via PT/YT tokens. Boros platform enables BTC funding rate trading.",
    website: "https://pendle.finance",
    token: "PT/YT",
    audits: 5,
    auditors: ["Spearbit", "Ackee", "Dedaub", "Decurity", "ChainSecurity"],
    mechanics: [
      "Split yield-bearing assets into Principal (PT) and Yield (YT) tokens",
      "Trade fixed-rate yields by buying PT at discount",
      "Speculate on variable yields by buying YT tokens",
      "Boros platform enables BTC perpetual funding rate trading"
    ],
    logo: "◉",
    color: "#F472B6",
    trend: [12.0, 9.5, 8.2, 11.0, 7.5, 9.0, 6.8, 8.5, 7.2, 7.8, 7.0, 7.4]
  },
  {
    id: 5,
    slug: null,
    urlSlug: "stacks",
    name: "Stacks Stacking",
    category: "L2 Stacking",
    apy: 7.0,
    apyRange: [7.0, 25.0],
    tvl: 1000,
    risk: "Low",
    chain: "Stacks L2",
    lockup: "14 days",
    minDeposit: 0.001,
    description: "Earn native BTC rewards by stacking STX. sBTC dual stacking boosts yields up to 5% APY.",
    website: "https://stacks.co",
    token: "STX/sBTC",
    audits: 3,
    auditors: ["Least Authority", "NCC Group", "Coinspect"],
    mechanics: [
      "Lock STX tokens to support Stacks consensus mechanism",
      "Earn native BTC rewards from Bitcoin miners",
      "sBTC dual stacking combines BTC + STX for boosted yields",
      "Liquid stacking via StackingDAO for stSTX token"
    ],
    logo: "⬡",
    color: "#38BDF8",
    trend: [8.0, 7.2, 6.5, 7.8, 6.8, 7.5, 6.2, 7.0, 7.2, 6.8, 7.0, 7.0]
  },
  {
    id: 6,
    slug: "aave-v3",
    urlSlug: "aave",
    name: "AAVE wBTC",
    category: "Lending",
    apy: 0.1,
    apyRange: [0.0, 6.0],
    tvl: 79,
    risk: "Low",
    chain: "Ethereum",
    lockup: "None",
    minDeposit: 0.001,
    description: "Supply wBTC to earn variable interest from borrowers. Largest DeFi lending protocol.",
    website: "https://aave.com",
    token: "aWBTC",
    audits: 15,
    auditors: ["OpenZeppelin", "Trail of Bits", "SigmaPrime", "ABDK", "PeckShield"],
    mechanics: [
      "Supply wBTC to lending pools and receive aWBTC tokens",
      "Earn variable interest from borrowers in real-time",
      "aWBTC balance increases automatically as interest accrues",
      "Withdraw anytime with no lockup period"
    ],
    logo: "◐",
    color: "#B4A0FF",
    trend: [0.35, 0.28, 0.32, 0.25, 0.3, 0.22, 0.28, 0.3, 0.26, 0.3, 0.28, 0.3]
  },
  {
    id: 7,
    slug: "morpho-blue",
    urlSlug: "morpho",
    name: "Morpho Blue",
    category: "Lending",
    apy: 7.3,
    apyRange: [4.0, 10.0],
    tvl: 3900,
    risk: "Low",
    chain: "Ethereum",
    lockup: "None",
    minDeposit: 0.001,
    description: "Optimized peer-to-peer lending with isolated risk pools. Coinbase uses it for $520M+ BTC-backed loans.",
    website: "https://morpho.org",
    token: "Supply Token",
    audits: 6,
    auditors: ["Spearbit", "Cantina", "ChainSecurity", "OpenZeppelin", "ABDK", "Cyfrin"],
    mechanics: [
      "Supply assets to isolated, permissionless lending markets",
      "Curated vaults by Gauntlet and Re7 for risk-adjusted yields",
      "Peer-to-peer matching for optimal rates",
      "No governance risk - immutable smart contracts"
    ],
    logo: "◑",
    color: "#67E8F9",
    trend: [8.5, 7.8, 6.5, 7.2, 8.0, 6.8, 7.5, 7.0, 7.8, 7.2, 7.4, 7.3]
  },
  {
    id: 8,
    slug: null,
    urlSlug: "bouncebit",
    name: "BounceBit",
    category: "CeDeFi",
    apy: 18.0,
    apyRange: [13.0, 43.0],
    tvl: 500,
    risk: "Medium",
    chain: "BounceBit",
    lockup: "30 days",
    minDeposit: 0.01,
    description: "CeDeFi restaking with institutional-grade custody. Prime product offers BUIDL + delta-neutral strategies.",
    website: "https://bouncebit.io",
    token: "BBTC",
    audits: 2,
    auditors: ["BlockSec", "PeckShield"],
    mechanics: [
      "Deposit BTC with institutional-grade Mainnet Digital custody",
      "Dual-token PoS staking with BTC + BB tokens",
      "Prime product uses BUIDL as collateral for basis trading",
      "Delta-neutral strategies target 10-24% annualized returns"
    ],
    logo: "◎",
    color: "#FBBF24",
    trend: [22.0, 18.5, 15.0, 20.0, 16.5, 19.0, 14.5, 17.0, 18.5, 16.0, 17.5, 18.0]
  },
  {
    id: 9,
    slug: null,
    urlSlug: "corn",
    name: "Corn Finance",
    category: "Yield Farming",
    apy: 5.0,
    apyRange: [3.0, 10.0],
    tvl: 120,
    risk: "High",
    chain: "Corn L2",
    lockup: "None",
    minDeposit: 0.005,
    description: "Ethereum L2 with Arbitrum stack secured by Babylon. BTCN hybrid token for gas fees.",
    website: "https://usecorn.com",
    token: "BTCN",
    audits: 2,
    auditors: ["Zellic", "Spearbit"],
    mechanics: [
      "Ethereum L2 built on Arbitrum Orbit stack",
      "BTCN hybrid token backed 1:1 by BTC for gas payments",
      "Secured by Babylon Bitcoin staking protocol",
      "PopCorn governance for yield allocation voting"
    ],
    logo: "◇",
    color: "#FB923C",
    trend: [4.2, 5.5, 4.8, 5.2, 4.5, 5.8, 5.0, 4.6, 5.2, 4.8, 5.0, 5.0]
  },
  {
    id: 10,
    slug: null,
    urlSlug: "mezo",
    name: "Mezo Network",
    category: "Economic Layer",
    apy: 15.0,
    apyRange: [15.0, 30.0],
    tvl: 82,
    risk: "Medium",
    chain: "Mezo",
    lockup: "Variable",
    minDeposit: 0.01,
    description: "Bitcoin L2 with 15-30% APY via MUSD vaults and upMUSD loops. Proof of HODL rewards.",
    website: "https://mezo.org",
    token: "MEZO",
    audits: 2,
    auditors: ["Trail of Bits", "Zellic"],
    mechanics: [
      "Proof of HODL mechanism rewards long-term BTC holders",
      "HODL score based on deposit value, timing, and lock duration",
      "MUSD Bitcoin-backed stablecoin for payments",
      "tBTC powers gas fees and collateral natively"
    ],
    logo: "⬢",
    color: "#E879F9",
    trend: [18.0, 14.5, 12.0, 16.0, 13.5, 15.5, 11.0, 14.0, 15.0, 13.0, 14.5, 15.0]
  },
  {
    id: 11,
    slug: "ethena",
    urlSlug: "ethena",
    name: "Ethena sUSDe",
    category: "Basis Trade",
    apy: 10.0,
    apyRange: [5.0, 13.0],
    tvl: 11890,
    risk: "High",
    chain: "Ethereum",
    lockup: "7 days",
    minDeposit: 0.01,
    description: "Delta-neutral basis trade with BTC/ETH collateral. sUSDe staking yields from funding rates.",
    website: "https://ethena.fi",
    token: "sUSDe",
    audits: 4,
    auditors: ["Quantstamp", "Pashov", "Code4rena", "Spearbit"],
    mechanics: [
      "Delta-neutral strategy using BTC/ETH spot + short perpetuals",
      "Earns yield from positive perpetual funding rates",
      "Stake USDe to receive sUSDe with auto-compounding yield",
      "Flexible allocation between funding rates and T-bills"
    ],
    logo: "◆",
    color: "#4ADE80",
    trend: [9.5, 7.8, 8.5, 6.5, 8.0, 7.2, 8.8, 7.5, 8.2, 7.8, 8.0, 8.0]
  },
  {
    id: 12,
    slug: "pstake-finance",
    urlSlug: "pstake",
    name: "pSTAKE yBTC",
    category: "Liquid Staking",
    apy: 1.0,
    apyRange: [0.5, 2.0],
    tvl: 6,
    risk: "Low",
    chain: "Ethereum",
    lockup: "None",
    minDeposit: 0.001,
    description: "Bitcoin liquid staking via Babylon. yBTC yield-bearing token with dual-token PSTAKE rewards.",
    website: "https://pstake.finance",
    token: "yBTC",
    audits: 5,
    auditors: ["Halborn", "Hexens", "Oak Security", "Immunefi", "Forta"],
    mechanics: [
      "Stake BTC via Babylon and receive yBTC liquid token",
      "yBTC automatically earns Babylon staking rewards",
      "Dual-token model: stake PSTAKE for boosted BTC rewards",
      "Use yBTC across DeFi while earning staking yield"
    ],
    logo: "◈",
    color: "#F87171",
    trend: [1.2, 0.85, 1.0, 0.75, 0.95, 0.8, 1.1, 0.9, 0.85, 0.95, 1.0, 1.0]
  },
  {
    id: 13,
    slug: "botanix-stbtc",
    urlSlug: "botanix",
    name: "Botanix",
    category: "L2 Stacking",
    apy: 7.0,
    apyRange: [6.0, 8.0],
    tvl: 14,
    risk: "Medium",
    chain: "Botanix L2",
    lockup: "None",
    minDeposit: 0.001,
    description: "EVM-equivalent Bitcoin L2 with stBTC liquid staking. 50% of gas fees redistributed to stakers.",
    website: "https://botanixlabs.xyz",
    token: "stBTC",
    audits: 2,
    auditors: ["Zellic", "Halborn"],
    mechanics: [
      "EVM-equivalent Bitcoin L2 secured by Spiderchain validators",
      "Stake BTC via Rover to receive stBTC liquid token",
      "50% of all network gas fees redistributed to stBTC holders",
      "Instant unstaking with no waiting period"
    ],
    logo: "❋",
    color: "#22C55E",
    trend: [5.5, 7.2, 6.0, 7.8, 5.8, 6.5, 7.5, 6.2, 7.0, 6.8, 7.2, 7.0]
  },
  {
    id: 14,
    slug: "lorenzo-protocol",
    urlSlug: "lorenzo",
    name: "Lorenzo Protocol",
    category: "Liquid Staking",
    apy: 5.0,
    apyRange: [3.0, 10.0],
    tvl: 1000,
    risk: "Medium",
    chain: "Multi-chain",
    lockup: "Variable",
    minDeposit: 0.001,
    description: "Bitcoin liquid staking secured by Babylon. Receive stBTC + YAT yield-accruing tokens across 21+ chains.",
    website: "https://lorenzo-protocol.xyz",
    token: "stBTC/YAT",
    audits: 3,
    auditors: ["Zellic", "PeckShield", "BlockSec"],
    mechanics: [
      "Stake BTC via Babylon and receive stBTC liquid token",
      "YAT (Yield Accruing Token) captures staking rewards separately",
      "Cross-chain functionality on 21+ blockchain networks",
      "On-Chain Traded Funds (OTFs) for structured products"
    ],
    logo: "◈",
    color: "#8B5CF6",
    trend: [5.8, 4.5, 5.2, 4.0, 5.5, 4.8, 5.0, 4.2, 4.8, 5.2, 4.9, 5.0]
  },
  {
    id: 15,
    slug: "bedrock-unibtc",
    urlSlug: "bedrock",
    name: "Bedrock uniBTC",
    category: "Restaking",
    apy: 9.0,
    apyRange: [6.0, 12.0],
    tvl: 620,
    risk: "Medium",
    chain: "Multi-chain",
    lockup: "None",
    minDeposit: 0.001,
    description: "Multi-asset liquid restaking protocol. Stake BTC to receive uniBTC across 19+ chains and 60+ DeFi partners.",
    website: "https://www.bedrock.technology",
    token: "uniBTC",
    audits: 4,
    auditors: ["Zellic", "Secure3", "BlockSec", "Veridise"],
    mechanics: [
      "First multi-asset liquid restaking protocol",
      "Stake BTC and receive uniBTC yield-generating token",
      "Supported on 19+ chains including Ethereum, BNB, Arbitrum",
      "5,000+ BTC staked with 250K+ active users"
    ],
    logo: "◉",
    color: "#3B82F6",
    trend: [7.5, 9.2, 8.0, 10.0, 7.8, 8.5, 9.5, 8.2, 9.0, 8.8, 9.2, 9.0]
  },
  {
    id: 16,
    slug: "pell-network",
    urlSlug: "pell",
    name: "Pell Network",
    category: "Restaking",
    apy: 8.0,
    apyRange: [5.0, 12.0],
    tvl: 530,
    risk: "Medium",
    chain: "Omnichain",
    lockup: "Variable",
    minDeposit: 0.01,
    description: "First omnichain Bitcoin restaking platform. Secure oracles, bridges, and AI compute with your BTC.",
    website: "https://pell.network",
    token: "PELL",
    audits: 3,
    auditors: ["Zellic", "BlockSec", "Secure3"],
    mechanics: [
      "Omnichain Bitcoin restaking for DVS (Decentralized Validated Services)",
      "Secure oracles, bridges, AI compute, and rollups with BTC",
      "Multiple yield streams from various AVS services",
      "500K+ users with cross-chain yield aggregation"
    ],
    logo: "⬢",
    color: "#10B981",
    trend: [6.5, 8.2, 7.0, 8.8, 6.8, 7.5, 8.5, 7.2, 8.0, 7.6, 8.2, 8.0]
  },
  {
    id: 17,
    slug: null,
    urlSlug: "core",
    name: "Core DAO",
    category: "L2 Stacking",
    apy: 6.0,
    apyRange: [4.0, 10.0],
    tvl: 629,
    risk: "Medium",
    chain: "Core",
    lockup: "Variable",
    minDeposit: 0.001,
    description: "Proof of Stake Layer for Bitcoin using Satoshi Plus consensus. Dual Staking with CORE and BTC rewards.",
    website: "https://coredao.org",
    token: "lstBTC",
    audits: 4,
    auditors: ["Halborn", "PeckShield", "Zellic", "Secure3"],
    mechanics: [
      "Satoshi Plus consensus combining DPoW and DPoS",
      "Stake both CORE tokens and BTC for dual rewards",
      "lstBTC liquid staked Bitcoin launching soon",
      "Secured by Bitcoin miners and CORE stakers"
    ],
    logo: "◎",
    color: "#F59E0B",
    trend: [5.2, 6.8, 5.5, 7.0, 5.8, 6.2, 6.8, 5.5, 6.0, 5.8, 6.2, 6.0]
  },
  {
    id: 18,
    slug: null,
    urlSlug: "bitlayer",
    name: "Bitlayer",
    category: "L2 Stacking",
    apy: 12.0,
    apyRange: [8.0, 20.0],
    tvl: 720,
    risk: "Medium",
    chain: "Bitlayer",
    lockup: "30 days",
    minDeposit: 0.01,
    description: "Bitcoin L2 using BitVM paradigm. BLBTC yield product offers up to 20% APY with institutional backing.",
    website: "https://bitlayer.org",
    token: "BLBTC",
    audits: 3,
    auditors: ["Trail of Bits", "Zellic", "BlockSec"],
    mechanics: [
      "First Bitcoin L2 using BitVM for trust-minimized bridging",
      "BLBTC yield-bearing BTC integrated with Solana DeFi",
      "BitVM Bridge Mainnet for secure cross-chain transfers",
      "200+ dApps with $30M institutional backing"
    ],
    logo: "◆",
    color: "#EC4899",
    trend: [14.0, 11.5, 10.0, 13.0, 10.8, 12.5, 9.5, 11.0, 12.5, 11.2, 12.0, 12.0]
  },
  {
    id: 19,
    slug: null,
    urlSlug: "bob",
    name: "BOB",
    category: "L2 Stacking",
    apy: 6.0,
    apyRange: [4.0, 10.0],
    tvl: 250,
    risk: "Medium",
    chain: "BOB L2",
    lockup: "Variable",
    minDeposit: 0.001,
    description: "Build on Bitcoin - hybrid L2 combining Bitcoin security with Ethereum DeFi. Multi-chain BTC yield layer.",
    website: "https://gobob.xyz",
    token: "BOB",
    audits: 3,
    auditors: ["OpenZeppelin", "Zellic", "Spearbit"],
    mechanics: [
      "Hybrid L2 with Bitcoin security and EVM compatibility",
      "Native Bitcoin Vaults with managed yield strategies",
      "Partners include Veda, Euler, Lombard, Gamma",
      "BitVM-based trust-minimized bridging"
    ],
    logo: "◇",
    color: "#F97316",
    trend: [7.0, 5.5, 6.2, 4.8, 5.8, 6.5, 5.2, 6.0, 5.5, 6.2, 5.8, 6.0]
  },
  {
    id: 20,
    slug: null,
    urlSlug: "rootstock",
    name: "Rootstock (RSK)",
    category: "L2 Stacking",
    apy: 8.0,
    apyRange: [5.0, 30.0],
    tvl: 286,
    risk: "Low",
    chain: "Rootstock",
    lockup: "None",
    minDeposit: 0.001,
    description: "Oldest Bitcoin sidechain (since 2018). EVM-compatible, secured by 80%+ of Bitcoin hashpower.",
    website: "https://rootstock.io",
    token: "rBTC",
    audits: 8,
    auditors: ["Trail of Bits", "OpenZeppelin", "Coinspect", "Bramah Systems", "Immunefi"],
    mechanics: [
      "Bitcoin sidechain secured by merge-mining with BTC miners",
      "Bridge BTC via Powpeg to receive rBTC 1:1",
      "Full EVM compatibility with 150+ dApps",
      "100% uptime since 2018, most battle-tested Bitcoin L2"
    ],
    logo: "◐",
    color: "#00B45A",
    trend: [9.5, 7.8, 8.5, 7.0, 8.2, 6.8, 7.8, 8.5, 7.5, 8.2, 7.8, 8.0]
  },
  {
    id: 21,
    slug: "swell-btc-lrt",
    urlSlug: "swell",
    name: "Swell swBTC",
    category: "Restaking",
    apy: 7.0,
    apyRange: [4.0, 10.0],
    tvl: 180,
    risk: "Medium",
    chain: "Ethereum",
    lockup: "10 days",
    minDeposit: 0.01,
    description: "First Bitcoin LRT (Liquid Restaking Token). Earn restaking rewards from Symbiotic, EigenLayer, and Karak.",
    website: "https://swellnetwork.io",
    token: "swBTC",
    audits: 4,
    auditors: ["Sigma Prime", "Mixbytes", "Pashov", "Cyfrin"],
    mechanics: [
      "Deposit WBTC and receive swBTC liquid restaking token",
      "Earn rewards from multiple restaking protocols simultaneously",
      "Aera-powered vault strategy with Gauntlet risk management",
      "10-day unstaking period for security"
    ],
    logo: "◑",
    color: "#38BDF8",
    trend: [5.8, 7.5, 6.2, 7.8, 5.5, 6.8, 7.2, 6.5, 7.0, 6.8, 7.2, 7.0]
  },
  {
    id: 22,
    slug: null,
    urlSlug: "merlin",
    name: "Merlin Chain",
    category: "L2 Stacking",
    apy: 8.0,
    apyRange: [6.0, 12.0],
    tvl: 150,
    risk: "Medium",
    chain: "Merlin",
    lockup: "Variable",
    minDeposit: 0.001,
    description: "First EVM-compatible ZK-rollup for Bitcoin. Merlin 2.0 offers 8% BTC staking APY with AI-driven features.",
    website: "https://merlinchain.io",
    token: "MERL",
    audits: 3,
    auditors: ["Zellic", "Secure3", "SlowMist"],
    mechanics: [
      "ZK-rollup architecture for Bitcoin scalability",
      "8% APY on native BTC staking",
      "20% MERL token allocation for staking rewards",
      "AI-driven chain abstraction in Merlin 2.0"
    ],
    logo: "⬡",
    color: "#7C3AED",
    trend: [7.0, 8.5, 6.5, 9.0, 7.2, 8.0, 8.8, 7.5, 8.2, 7.8, 8.0, 8.0]
  },
  {
    id: 23,
    slug: "chakra",
    urlSlug: "chakra",
    name: "Chakra",
    category: "Restaking",
    apy: 6.0,
    apyRange: [4.0, 10.0],
    tvl: 117,
    risk: "Medium",
    chain: "Multi-chain",
    lockup: "Variable",
    minDeposit: 0.01,
    description: "Modular settlement network for Bitcoin liquidity. Cross-chain restaking rewards across 20+ blockchains.",
    website: "https://chakrachain.io",
    token: "CHAKRA",
    audits: 2,
    auditors: ["Zellic", "BlockSec"],
    mechanics: [
      "Universal BTC settlement layer for cross-chain liquidity",
      "Route BTC and BTC-derived assets across 20+ chains",
      "Cross-chain PoS architecture for restaking rewards",
      "50K+ users with modular settlement design"
    ],
    logo: "◈",
    color: "#E11D48",
    trend: [4.8, 6.5, 5.2, 6.8, 5.5, 6.2, 5.8, 6.5, 5.8, 6.0, 5.5, 6.0]
  },
  {
    id: 24,
    slug: "alex",
    urlSlug: "alex",
    name: "ALEX Lab",
    category: "Yield Farming",
    apy: 25.0,
    apyRange: [10.0, 117.0],
    tvl: 80,
    risk: "High",
    chain: "Stacks",
    lockup: "None",
    minDeposit: 0.001,
    description: "Super App for Bitcoin on Stacks. DEX, swaps, liquidity pools, staking, yield farming with sBTC.",
    website: "https://alexlab.co",
    token: "ALEX",
    audits: 3,
    auditors: ["CoinFabrik", "Least Authority", "Immunefi"],
    mechanics: [
      "Comprehensive DeFi hub on Stacks L2",
      "DEX with AMM pools reaching up to 117% APR",
      "Bitcoin Oracle for on-chain BTC price feeds",
      "$1B+ transaction volume with DAMM coming Q4"
    ],
    logo: "◉",
    color: "#FF6B00",
    trend: [30.0, 22.0, 18.0, 28.0, 20.0, 26.0, 17.0, 23.0, 25.0, 21.0, 24.0, 25.0]
  },
  {
    id: 25,
    slug: null,
    urlSlug: "citrea",
    name: "Citrea",
    category: "L2 Stacking",
    apy: 5.0,
    apyRange: [3.0, 8.0],
    tvl: 50,
    risk: "High",
    chain: "Citrea",
    lockup: "Variable",
    minDeposit: 0.01,
    description: "First production-grade ZK-rollup L2 on Bitcoin. Native BTC lending via Morpho with cBTC collateral.",
    website: "https://citrea.xyz",
    token: "cBTC",
    audits: 2,
    auditors: ["Zellic", "Trail of Bits"],
    mechanics: [
      "zkEVM rollup with Bitcoin L1 settlement",
      "Clementine bridge for trust-minimized BTC transfers",
      "Native lending markets via Morpho integration",
      "ctUSD stablecoin backed by cBTC collateral"
    ],
    logo: "◇",
    color: "#06B6D4",
    trend: [4.2, 5.5, 4.0, 5.8, 4.5, 5.2, 4.8, 5.5, 5.0, 4.8, 5.2, 5.0]
  },
  {
    id: 26,
    slug: null,
    urlSlug: "ledn",
    name: "Ledn",
    category: "CeFi Lending",
    apy: 5.25,
    apyRange: [3.0, 8.5],
    tvl: 500,
    risk: "Low",
    chain: "Centralized",
    lockup: "None",
    minDeposit: 0.0001,
    description: "Bitcoin-focused CeFi lending. Growth Accounts offer up to 5.25% on BTC. Never paused withdrawals.",
    website: "https://ledn.io",
    token: "BTC",
    audits: 2,
    auditors: ["Armanino", "SOC 2 Type 2"],
    mechanics: [
      "CeFi lending with BitGo custody ($100M insurance)",
      "Growth Accounts earn yield on deposited BTC",
      "Bitcoin-backed loans at 50% LTV",
      "SOC 2 Type 2 compliance, daily compounding"
    ],
    logo: "◐",
    color: "#14B8A6",
    trend: [5.5, 5.0, 5.3, 4.8, 5.4, 5.1, 5.6, 5.0, 5.3, 5.15, 5.4, 5.25]
  },
  {
    id: 27,
    slug: "nexo",
    urlSlug: "nexo",
    name: "Nexo",
    category: "CeFi Lending",
    apy: 5.0,
    apyRange: [4.0, 7.0],
    tvl: 400,
    risk: "Low",
    chain: "Centralized",
    lockup: "Flexible",
    minDeposit: 0.0001,
    description: "Crypto lending platform with flexible and fixed-term savings. Loyalty tiers boost BTC yields up to 7%.",
    website: "https://nexo.com",
    token: "NEXO",
    audits: 3,
    auditors: ["Armanino", "BitGo", "Ledger"],
    mechanics: [
      "Tiered yield system based on NEXO token holdings",
      "Flexible savings with instant withdrawals",
      "Fixed-term options for higher rates",
      "Interest-free loans for BTC/ETH holders"
    ],
    logo: "◑",
    color: "#0052FF",
    trend: [5.2, 4.5, 5.0, 4.2, 5.3, 4.7, 5.1, 4.6, 5.0, 4.8, 5.2, 5.0]
  },
  {
    id: 28,
    slug: "compound-finance",
    urlSlug: "compound",
    name: "Compound",
    category: "Lending",
    apy: 4.5,
    apyRange: [2.0, 8.0],
    tvl: 2500,
    risk: "Low",
    chain: "Ethereum",
    lockup: "None",
    minDeposit: 0.001,
    description: "Pioneer of algorithmic money markets. Compound V3 supports wBTC as collateral for borrowing.",
    website: "https://compound.finance",
    token: "cWBTC",
    audits: 10,
    auditors: ["OpenZeppelin", "Trail of Bits", "Gauntlet", "ChainSecurity", "ABDK"],
    mechanics: [
      "Algorithmic interest rates based on supply/demand",
      "Supply wBTC to earn variable interest",
      "Use wBTC as collateral to borrow stablecoins",
      "Battle-tested since 2018 with billions in TVL"
    ],
    logo: "◎",
    color: "#00D395",
    trend: [4.8, 4.0, 4.5, 3.8, 4.6, 4.2, 4.8, 4.0, 4.4, 4.3, 4.6, 4.5]
  },
];

export const CATEGORIES = ["All", "Native Staking", "Liquid Staking", "Restaking", "Lending", "CeFi Lending", "Yield Vault", "Yield Trading", "Yield Farming", "CeDeFi", "L2 Stacking", "Basis Trade", "Economic Layer"];
export const RISK_LEVELS = ["All", "Low", "Medium", "High"];
export const SORT_OPTIONS = [
  { label: "Highest APY", value: "apy-desc" },
  { label: "Lowest APY", value: "apy-asc" },
  { label: "Highest TVL", value: "tvl-desc" },
  { label: "Lowest Risk", value: "risk-asc" },
  { label: "Name A-Z", value: "name-asc" },
];

export const STRATEGIES = [
  { name: "Native", description: "Pure Bitcoin staking. No wrapping, no bridges. Native BTC yields from L2s.", icon: "₿", allocations: [{ id: 1, pct: 35 }, { id: 5, pct: 30 }, { id: 13, pct: 25 }, { id: 10, pct: 10 }], expectedApy: 5.5, riskLevel: "Low" },
  { name: "Mixed", description: "Diversified exposure across lending, staking, and yield vaults.", icon: "⚖️", allocations: [{ id: 7, pct: 25 }, { id: 3, pct: 25 }, { id: 2, pct: 20 }, { id: 1, pct: 15 }, { id: 13, pct: 15 }], expectedApy: 4.3, riskLevel: "Medium" },
  { name: "YieldMaxxer", description: "Maximum APY. Yield trading, basis trades, and CeDeFi strategies.", icon: "🚀", allocations: [{ id: 4, pct: 30 }, { id: 8, pct: 25 }, { id: 3, pct: 25 }, { id: 11, pct: 20 }], expectedApy: 10.0, riskLevel: "High" },
];

// Fallback BTC price if APIs fail
export const FALLBACK_BTC_PRICE = 97842;
