// Protocol configuration with DeFiLlama slugs for TVL fetching
// Data updated: February 2026
export const PROTOCOL_CONFIG = [
  {
    id: 1,
    slug: "babylon",
    urlSlug: "babylon",
    name: "Babylon Labs",
    category: "Native Staking",
    apy: 1.0,
    apyRange: [0.5, 3.0],
    tvl: 5000,
    risk: "Low",
    chain: "Bitcoin",
    lockup: "21 days",
    minDeposit: 0.01,
    description: "Native BTC staking securing PoS chains. Rewards paid in BABY tokens. No wrapping, no bridges.",
    website: "https://babylonlabs.io",
    token: "BABY",
    audits: 4,
    auditors: ["Halborn", "CertiK", "Zellic", "Trail of Bits"],
    mechanics: [
      "Stake BTC directly on Bitcoin mainnet via time-lock scripts",
      "Secure proof-of-stake networks and earn BABY token rewards",
      "No wrapping, bridging, or custody transfer required",
      "Slashing protection through cryptographic finality gadgets"
    ],
    logo: "₿",
    color: "#F7931A",
    trend: [0.6, 0.7, 0.8, 0.85, 0.9, 0.95, 0.98, 1.0]
  },
  {
    id: 2,
    slug: "lombard",
    urlSlug: "lombard",
    name: "Lombard Finance",
    category: "Liquid Staking",
    apy: 0.4,
    apyRange: [0.3, 1.0],
    tvl: 1040,
    risk: "Low",
    chain: "Ethereum",
    lockup: "None",
    minDeposit: 0.0002,
    description: "LBTC liquid staking token via Babylon. Full DeFi composability. Up to 15% APY with BARD staking.",
    website: "https://lombard.finance",
    token: "LBTC",
    audits: 4,
    auditors: ["Halborn", "Zellic", "Spearbit", "Code4rena"],
    mechanics: [
      "Deposit BTC and receive LBTC liquid staking token 1:1",
      "LBTC earns Babylon staking rewards automatically",
      "Use LBTC across DeFi for additional yield opportunities",
      "Stake BARD tokens for boosted APY up to 15%"
    ],
    logo: "◆",
    color: "#6EE7B7",
    trend: [0.35, 0.36, 0.37, 0.38, 0.39, 0.4, 0.4, 0.4]
  },
  {
    id: 3,
    slug: "solv-protocol",
    urlSlug: "solvbtc",
    name: "SolvBTC",
    category: "Yield Vault",
    apy: 8.5,
    apyRange: [5.0, 12.0],
    tvl: 2500,
    risk: "Medium",
    chain: "Multi-chain",
    lockup: "7 days",
    minDeposit: 0.005,
    description: "Cross-chain yield optimization via xSolvBTC and SolvBTC.CORE. 1:1 backed with Chainlink PoR verification.",
    website: "https://solv.finance",
    token: "SolvBTC",
    audits: 3,
    auditors: ["Quantstamp", "SlowMist", "Secbit"],
    mechanics: [
      "Deposit BTC to mint SolvBTC universal reserve token",
      "Automated yield strategies across multiple chains",
      "Chainlink Proof of Reserve verifies 1:1 backing every 10 min",
      "xSolvBTC and SolvBTC.CORE for liquid staking rewards"
    ],
    logo: "◈",
    color: "#A78BFA",
    trend: [6.0, 6.5, 7.0, 7.5, 8.0, 8.2, 8.4, 8.5]
  },
  {
    id: 4,
    slug: "pendle",
    urlSlug: "pendle",
    name: "Pendle BTC",
    category: "Yield Trading",
    apy: 10.0,
    apyRange: [6.0, 14.0],
    tvl: 5800,
    risk: "High",
    chain: "Ethereum",
    lockup: "Variable",
    minDeposit: 0.01,
    description: "Tokenized yield trading via PT/YT tokens. Boros platform enables BTC funding rate trading.",
    website: "https://pendle.finance",
    token: "PT/YT",
    audits: 5,
    auditors: ["Spearbit", "Ackee", "Dedaub", "Decurity", "ChainSecurity"],
    mechanics: [
      "Split yield-bearing assets into Principal (PT) and Yield (YT) tokens",
      "Trade fixed-rate yields by buying PT at discount",
      "Speculate on variable yields by buying YT tokens",
      "Boros platform enables BTC perpetual funding rate trading"
    ],
    logo: "◉",
    color: "#F472B6",
    trend: [7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 9.8, 10.0]
  },
  {
    id: 5,
    slug: null,
    urlSlug: "stacks",
    name: "Stacks Stacking",
    category: "L2 Stacking",
    apy: 7.0,
    apyRange: [5.0, 10.0],
    tvl: 412,
    risk: "Low",
    chain: "Stacks L2",
    lockup: "14 days",
    minDeposit: 0.001,
    description: "Earn native BTC rewards by stacking STX. sBTC dual stacking boosts yields up to 5% APY.",
    website: "https://stacks.co",
    token: "STX/sBTC",
    audits: 3,
    auditors: ["Least Authority", "NCC Group", "Coinspect"],
    mechanics: [
      "Lock STX tokens to support Stacks consensus mechanism",
      "Earn native BTC rewards from Bitcoin miners",
      "sBTC dual stacking combines BTC + STX for boosted yields",
      "Liquid stacking via StackingDAO for stSTX token"
    ],
    logo: "⬡",
    color: "#38BDF8",
    trend: [5.5, 6.0, 6.2, 6.5, 6.8, 7.0, 7.0, 7.0]
  },
  {
    id: 6,
    slug: "aave-v3",
    urlSlug: "aave",
    name: "AAVE wBTC",
    category: "Lending",
    apy: 0.3,
    apyRange: [0.1, 1.5],
    tvl: 4930,
    risk: "Low",
    chain: "Ethereum",
    lockup: "None",
    minDeposit: 0.001,
    description: "Supply wBTC to earn variable interest from borrowers. Largest DeFi lending protocol.",
    website: "https://aave.com",
    token: "aWBTC",
    audits: 15,
    auditors: ["OpenZeppelin", "Trail of Bits", "SigmaPrime", "ABDK", "PeckShield"],
    mechanics: [
      "Supply wBTC to lending pools and receive aWBTC tokens",
      "Earn variable interest from borrowers in real-time",
      "aWBTC balance increases automatically as interest accrues",
      "Withdraw anytime with no lockup period"
    ],
    logo: "◐",
    color: "#B4A0FF",
    trend: [0.2, 0.22, 0.25, 0.27, 0.28, 0.29, 0.3, 0.3]
  },
  {
    id: 7,
    slug: "morpho-blue",
    urlSlug: "morpho",
    name: "Morpho Blue",
    category: "Lending",
    apy: 7.3,
    apyRange: [4.0, 10.0],
    tvl: 8000,
    risk: "Low",
    chain: "Ethereum",
    lockup: "None",
    minDeposit: 0.001,
    description: "Optimized peer-to-peer lending with isolated risk pools. Coinbase uses it for $520M+ BTC-backed loans.",
    website: "https://morpho.org",
    token: "Supply Token",
    audits: 6,
    auditors: ["Spearbit", "Cantina", "ChainSecurity", "OpenZeppelin", "ABDK", "Cyfrin"],
    mechanics: [
      "Supply assets to isolated, permissionless lending markets",
      "Curated vaults by Gauntlet and Re7 for risk-adjusted yields",
      "Peer-to-peer matching for optimal rates",
      "No governance risk - immutable smart contracts"
    ],
    logo: "◑",
    color: "#67E8F9",
    trend: [5.0, 5.5, 6.0, 6.5, 7.0, 7.1, 7.2, 7.3]
  },
  {
    id: 8,
    slug: "bouncebit",
    urlSlug: "bouncebit",
    name: "BounceBit",
    category: "CeDeFi",
    apy: 10.0,
    apyRange: [5.0, 18.0],
    tvl: 514,
    risk: "Medium",
    chain: "BounceBit",
    lockup: "30 days",
    minDeposit: 0.01,
    description: "CeDeFi restaking with institutional-grade custody. Prime product offers BUIDL + delta-neutral strategies.",
    website: "https://bouncebit.io",
    token: "BBTC",
    audits: 2,
    auditors: ["BlockSec", "PeckShield"],
    mechanics: [
      "Deposit BTC with institutional-grade Mainnet Digital custody",
      "Dual-token PoS staking with BTC + BB tokens",
      "Prime product uses BUIDL as collateral for basis trading",
      "Delta-neutral strategies target 10-24% annualized returns"
    ],
    logo: "◎",
    color: "#FBBF24",
    trend: [7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 9.8, 10.0]
  },
  {
    id: 9,
    slug: "corn",
    urlSlug: "corn",
    name: "Corn Finance",
    category: "Yield Farming",
    apy: 5.0,
    apyRange: [3.0, 10.0],
    tvl: 120,
    risk: "High",
    chain: "Corn L2",
    lockup: "None",
    minDeposit: 0.005,
    description: "Ethereum L2 with Arbitrum stack secured by Babylon. BTCN hybrid token for gas fees.",
    website: "https://usecorn.com",
    token: "BTCN",
    audits: 2,
    auditors: ["Zellic", "Spearbit"],
    mechanics: [
      "Ethereum L2 built on Arbitrum Orbit stack",
      "BTCN hybrid token backed 1:1 by BTC for gas payments",
      "Secured by Babylon Bitcoin staking protocol",
      "PopCorn governance for yield allocation voting"
    ],
    logo: "◇",
    color: "#FB923C",
    trend: [3.5, 4.0, 4.2, 4.5, 4.7, 4.8, 4.9, 5.0]
  },
  {
    id: 10,
    slug: "mezo",
    urlSlug: "mezo",
    name: "Mezo Network",
    category: "Economic Layer",
    apy: 4.0,
    apyRange: [2.0, 8.0],
    tvl: 82,
    risk: "Medium",
    chain: "Mezo",
    lockup: "Variable",
    minDeposit: 0.01,
    description: "Bitcoin L2 economic layer with Proof of HODL rewards. MUSD Bitcoin-backed stablecoin.",
    website: "https://mezo.org",
    token: "MEZO",
    audits: 2,
    auditors: ["Trail of Bits", "Zellic"],
    mechanics: [
      "Proof of HODL mechanism rewards long-term BTC holders",
      "HODL score based on deposit value, timing, and lock duration",
      "MUSD Bitcoin-backed stablecoin for payments",
      "tBTC powers gas fees and collateral natively"
    ],
    logo: "⬢",
    color: "#E879F9",
    trend: [2.5, 2.8, 3.0, 3.2, 3.5, 3.7, 3.9, 4.0]
  },
  {
    id: 11,
    slug: "ethena",
    urlSlug: "ethena",
    name: "Ethena sUSDe",
    category: "Basis Trade",
    apy: 8.0,
    apyRange: [5.0, 12.0],
    tvl: 3800,
    risk: "High",
    chain: "Ethereum",
    lockup: "7 days",
    minDeposit: 0.01,
    description: "Delta-neutral basis trade with BTC/ETH collateral. sUSDe staking yields from funding rates.",
    website: "https://ethena.fi",
    token: "sUSDe",
    audits: 4,
    auditors: ["Quantstamp", "Pashov", "Code4rena", "Spearbit"],
    mechanics: [
      "Delta-neutral strategy using BTC/ETH spot + short perpetuals",
      "Earns yield from positive perpetual funding rates",
      "Stake USDe to receive sUSDe with auto-compounding yield",
      "Flexible allocation between funding rates and T-bills"
    ],
    logo: "◆",
    color: "#4ADE80",
    trend: [6.0, 6.5, 7.0, 7.3, 7.5, 7.7, 7.9, 8.0]
  },
  {
    id: 12,
    slug: "pstake",
    urlSlug: "pstake",
    name: "pSTAKE yBTC",
    category: "Liquid Staking",
    apy: 1.0,
    apyRange: [0.5, 2.0],
    tvl: 6,
    risk: "Low",
    chain: "Ethereum",
    lockup: "None",
    minDeposit: 0.001,
    description: "Bitcoin liquid staking via Babylon. yBTC yield-bearing token with dual-token PSTAKE rewards.",
    website: "https://pstake.finance",
    token: "yBTC",
    audits: 5,
    auditors: ["Halborn", "Hexens", "Oak Security", "Immunefi", "Forta"],
    mechanics: [
      "Stake BTC via Babylon and receive yBTC liquid token",
      "yBTC automatically earns Babylon staking rewards",
      "Dual-token model: stake PSTAKE for boosted BTC rewards",
      "Use yBTC across DeFi while earning staking yield"
    ],
    logo: "◈",
    color: "#F87171",
    trend: [0.6, 0.7, 0.8, 0.85, 0.9, 0.95, 0.98, 1.0]
  },
  {
    id: 13,
    slug: "botanix-stbtc",
    urlSlug: "botanix",
    name: "Botanix",
    category: "L2 Stacking",
    apy: 7.0,
    apyRange: [6.0, 8.0],
    tvl: 14,
    risk: "Medium",
    chain: "Botanix L2",
    lockup: "None",
    minDeposit: 0.001,
    description: "EVM-equivalent Bitcoin L2 with stBTC liquid staking. 50% of gas fees redistributed to stakers.",
    website: "https://botanixlabs.xyz",
    token: "stBTC",
    audits: 2,
    auditors: ["Zellic", "Halborn"],
    mechanics: [
      "EVM-equivalent Bitcoin L2 secured by Spiderchain validators",
      "Stake BTC via Rover to receive stBTC liquid token",
      "50% of all network gas fees redistributed to stBTC holders",
      "Instant unstaking with no waiting period"
    ],
    logo: "❋",
    color: "#22C55E",
    trend: [4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 6.8, 7.0]
  },
];

export const CATEGORIES = ["All", "Native Staking", "Liquid Staking", "Lending", "Yield Vault", "Yield Trading", "Yield Farming", "CeDeFi", "L2 Stacking", "Basis Trade", "Economic Layer"];
export const RISK_LEVELS = ["All", "Low", "Medium", "High"];
export const SORT_OPTIONS = [
  { label: "Highest APY", value: "apy-desc" },
  { label: "Lowest APY", value: "apy-asc" },
  { label: "Highest TVL", value: "tvl-desc" },
  { label: "Lowest Risk", value: "risk-asc" },
  { label: "Name A-Z", value: "name-asc" },
];

export const STRATEGIES = [
  { name: "Native", description: "Pure Bitcoin staking. No wrapping, no bridges. Native BTC yields from L2s.", icon: "₿", allocations: [{ id: 1, pct: 35 }, { id: 5, pct: 30 }, { id: 13, pct: 25 }, { id: 10, pct: 10 }], expectedApy: 4.6, riskLevel: "Low" },
  { name: "Mixed", description: "Diversified exposure across lending, staking, and yield vaults.", icon: "⚖️", allocations: [{ id: 7, pct: 25 }, { id: 3, pct: 25 }, { id: 2, pct: 20 }, { id: 1, pct: 15 }, { id: 13, pct: 15 }], expectedApy: 5.8, riskLevel: "Medium" },
  { name: "YieldMaxxer", description: "Maximum APY. Yield trading, basis trades, and CeDeFi strategies.", icon: "🚀", allocations: [{ id: 4, pct: 30 }, { id: 8, pct: 25 }, { id: 3, pct: 25 }, { id: 11, pct: 20 }], expectedApy: 9.2, riskLevel: "High" },
];

// Fallback BTC price if APIs fail
export const FALLBACK_BTC_PRICE = 97842;
