// Protocol configuration with DeFiLlama slugs for TVL fetching
// Data updated: February 2026
export const PROTOCOL_CONFIG = [
  {
    id: 1,
    slug: "babylon",
    name: "Babylon Labs",
    category: "Native Staking",
    apy: 1.0,
    apyRange: [0.5, 3.0],
    tvl: 5000,
    risk: "Low",
    chain: "Bitcoin",
    lockup: "21 days",
    minDeposit: 0.01,
    description: "Native BTC staking securing PoS chains. Rewards paid in BABY tokens. No wrapping, no bridges.",
    audits: 4,
    logo: "₿",
    color: "#F7931A",
    trend: [0.6, 0.7, 0.8, 0.85, 0.9, 0.95, 0.98, 1.0]
  },
  {
    id: 2,
    slug: "lombard",
    name: "Lombard Finance",
    category: "Liquid Staking",
    apy: 0.4,
    apyRange: [0.3, 1.0],
    tvl: 1040,
    risk: "Low",
    chain: "Ethereum",
    lockup: "None",
    minDeposit: 0.0002,
    description: "LBTC liquid staking token via Babylon. Full DeFi composability. Up to 15% APY with BARD staking.",
    audits: 4,
    logo: "◆",
    color: "#6EE7B7",
    trend: [0.35, 0.36, 0.37, 0.38, 0.39, 0.4, 0.4, 0.4]
  },
  {
    id: 3,
    slug: "solv-protocol",
    name: "SolvBTC",
    category: "Yield Vault",
    apy: 8.5,
    apyRange: [5.0, 12.0],
    tvl: 2500,
    risk: "Medium",
    chain: "Multi-chain",
    lockup: "7 days",
    minDeposit: 0.005,
    description: "Cross-chain yield optimization via xSolvBTC and SolvBTC.CORE. 1:1 backed with Chainlink PoR verification.",
    audits: 3,
    logo: "◈",
    color: "#A78BFA",
    trend: [6.0, 6.5, 7.0, 7.5, 8.0, 8.2, 8.4, 8.5]
  },
  {
    id: 4,
    slug: "pendle",
    name: "Pendle BTC",
    category: "Yield Trading",
    apy: 10.0,
    apyRange: [6.0, 14.0],
    tvl: 5800,
    risk: "High",
    chain: "Ethereum",
    lockup: "Variable",
    minDeposit: 0.01,
    description: "Tokenized yield trading via PT/YT tokens. Boros platform enables BTC funding rate trading.",
    audits: 5,
    logo: "◉",
    color: "#F472B6",
    trend: [7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 9.8, 10.0]
  },
  {
    id: 5,
    slug: null,
    name: "Stacks Stacking",
    category: "L2 Stacking",
    apy: 7.0,
    apyRange: [5.0, 10.0],
    tvl: 412,
    risk: "Low",
    chain: "Stacks L2",
    lockup: "14 days",
    minDeposit: 0.001,
    description: "Earn native BTC rewards by stacking STX. sBTC dual stacking boosts yields up to 5% APY.",
    audits: 3,
    logo: "⬡",
    color: "#38BDF8",
    trend: [5.5, 6.0, 6.2, 6.5, 6.8, 7.0, 7.0, 7.0]
  },
  {
    id: 6,
    slug: "aave-v3",
    name: "AAVE wBTC",
    category: "Lending",
    apy: 0.3,
    apyRange: [0.1, 1.5],
    tvl: 4930,
    risk: "Low",
    chain: "Ethereum",
    lockup: "None",
    minDeposit: 0.001,
    description: "Supply wBTC to earn variable interest from borrowers. Largest DeFi lending protocol.",
    audits: 15,
    logo: "◐",
    color: "#B4A0FF",
    trend: [0.2, 0.22, 0.25, 0.27, 0.28, 0.29, 0.3, 0.3]
  },
  {
    id: 7,
    slug: "morpho-blue",
    name: "Morpho Blue",
    category: "Lending",
    apy: 7.3,
    apyRange: [4.0, 10.0],
    tvl: 8000,
    risk: "Low",
    chain: "Ethereum",
    lockup: "None",
    minDeposit: 0.001,
    description: "Optimized peer-to-peer lending with isolated risk pools. Coinbase uses it for $520M+ BTC-backed loans.",
    audits: 6,
    logo: "◑",
    color: "#67E8F9",
    trend: [5.0, 5.5, 6.0, 6.5, 7.0, 7.1, 7.2, 7.3]
  },
  {
    id: 8,
    slug: "bouncebit",
    name: "BounceBit",
    category: "CeDeFi",
    apy: 10.0,
    apyRange: [5.0, 18.0],
    tvl: 514,
    risk: "Medium",
    chain: "BounceBit",
    lockup: "30 days",
    minDeposit: 0.01,
    description: "CeDeFi restaking with institutional-grade custody. Prime product offers BUIDL + delta-neutral strategies.",
    audits: 2,
    logo: "◎",
    color: "#FBBF24",
    trend: [7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 9.8, 10.0]
  },
  {
    id: 9,
    slug: "corn",
    name: "Corn Finance",
    category: "Yield Farming",
    apy: 5.0,
    apyRange: [3.0, 10.0],
    tvl: 120,
    risk: "High",
    chain: "Corn L2",
    lockup: "None",
    minDeposit: 0.005,
    description: "Ethereum L2 with Arbitrum stack secured by Babylon. BTCN hybrid token for gas fees.",
    audits: 2,
    logo: "◇",
    color: "#FB923C",
    trend: [3.5, 4.0, 4.2, 4.5, 4.7, 4.8, 4.9, 5.0]
  },
  {
    id: 10,
    slug: "mezo",
    name: "Mezo Network",
    category: "Economic Layer",
    apy: 4.0,
    apyRange: [2.0, 8.0],
    tvl: 82,
    risk: "Medium",
    chain: "Mezo",
    lockup: "Variable",
    minDeposit: 0.01,
    description: "Bitcoin L2 economic layer with Proof of HODL rewards. MUSD Bitcoin-backed stablecoin.",
    audits: 2,
    logo: "⬢",
    color: "#E879F9",
    trend: [2.5, 2.8, 3.0, 3.2, 3.5, 3.7, 3.9, 4.0]
  },
  {
    id: 11,
    slug: "ethena",
    name: "Ethena sUSDe",
    category: "Basis Trade",
    apy: 8.0,
    apyRange: [5.0, 12.0],
    tvl: 3800,
    risk: "High",
    chain: "Ethereum",
    lockup: "7 days",
    minDeposit: 0.01,
    description: "Delta-neutral basis trade with BTC/ETH collateral. sUSDe staking yields from funding rates.",
    audits: 4,
    logo: "◆",
    color: "#4ADE80",
    trend: [6.0, 6.5, 7.0, 7.3, 7.5, 7.7, 7.9, 8.0]
  },
  {
    id: 12,
    slug: "pstake",
    name: "pSTAKE yBTC",
    category: "Liquid Staking",
    apy: 1.0,
    apyRange: [0.5, 2.0],
    tvl: 6,
    risk: "Low",
    chain: "Ethereum",
    lockup: "None",
    minDeposit: 0.001,
    description: "Bitcoin liquid staking via Babylon. yBTC yield-bearing token with dual-token PSTAKE rewards.",
    audits: 5,
    logo: "◈",
    color: "#F87171",
    trend: [0.6, 0.7, 0.8, 0.85, 0.9, 0.95, 0.98, 1.0]
  },
  {
    id: 13,
    slug: "botanix-stbtc",
    name: "Botanix",
    category: "L2 Stacking",
    apy: 7.0,
    apyRange: [6.0, 8.0],
    tvl: 14,
    risk: "Medium",
    chain: "Botanix L2",
    lockup: "None",
    minDeposit: 0.001,
    description: "EVM-equivalent Bitcoin L2 with stBTC liquid staking. 50% of gas fees redistributed to stakers.",
    audits: 2,
    logo: "❋",
    color: "#22C55E",
    trend: [4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 6.8, 7.0]
  },
];

export const CATEGORIES = ["All", "Native Staking", "Liquid Staking", "Lending", "Yield Vault", "Yield Trading", "Yield Farming", "CeDeFi", "L2 Stacking", "Basis Trade", "Economic Layer"];
export const RISK_LEVELS = ["All", "Low", "Medium", "High"];
export const SORT_OPTIONS = [
  { label: "Highest APY", value: "apy-desc" },
  { label: "Lowest APY", value: "apy-asc" },
  { label: "Highest TVL", value: "tvl-desc" },
  { label: "Lowest Risk", value: "risk-asc" },
  { label: "Name A-Z", value: "name-asc" },
];

export const STRATEGIES = [
  { name: "Conservative", description: "Low risk, stable yields. Battle-tested lending protocols.", icon: "🛡️", allocations: [{ id: 6, pct: 30 }, { id: 7, pct: 30 }, { id: 5, pct: 25 }, { id: 1, pct: 15 }], expectedApy: 4.2, riskLevel: "Low" },
  { name: "Balanced", description: "Mixed risk for moderate yields. Core staking with yield vaults.", icon: "⚖️", allocations: [{ id: 3, pct: 25 }, { id: 7, pct: 25 }, { id: 8, pct: 20 }, { id: 5, pct: 15 }, { id: 13, pct: 15 }], expectedApy: 7.5, riskLevel: "Medium" },
  { name: "Aggressive", description: "Maximum yield. High-APY protocols with yield trading.", icon: "🔥", allocations: [{ id: 4, pct: 30 }, { id: 8, pct: 25 }, { id: 11, pct: 25 }, { id: 3, pct: 20 }], expectedApy: 9.2, riskLevel: "High" },
];

// Fallback BTC price if APIs fail
export const FALLBACK_BTC_PRICE = 97842;
